---
    # tasks file for define_content
     - name: Make variable
       shell: cat /etc/issue | tr -d 'n\\l'
       register: cat_issue
    
     - name: echo file
       debug:
         msg: "Content is {{cat_issue.stdout}}, hostname is {{ansible_hostname}} "
