---
# tasks file for Delete_AWS_EC2_instances
    - name: Terminate instances
      hosts: localhost
      tasks:
        - name: Terminate instances that were previously launched
          ec2:
            state: 'absent'
            instance_ids: 'i-041e34ae2b4e9b84a'