##########################################################
# DO Community Playbook: Create file and define variable.
##########################################################
---
    - name: Create file
      hosts: iaas
      become: yes
      vars_files:
        - vars/default
    
      roles:
        - Create_file
    
    - name: Define variable
      hosts: servers_all
      become: yes
      vars_files:
        - vars/default
     
      roles:
        - Define_content
